### ISSUE TITLE
レポートを提出する。

### ISSUE THREAD

**Issue by wkentaro** [utmech-2014/utmech-ros-enshu#20]
12/31まで。 @utmech-2014/contributors

**Comment by jiangjun0105** [comment]
Do I have to send it too?

**Comment by wkentaro** [comment]
I don't think so.
You didn't attend the training classes, do you?

**Comment by wkentaro** [comment]
I don't think so.
You didn't attend the training classes, do you?

**Comment by jiangjun0105** [comment]
No, I didn't take it. 
OK, thank you!
